export enum ShopTypes {
    HANDLE_SET_PRODUCTS = 'HANDLE_SET_PRODUCTS',
    HANDLE_SET_CART = 'HANDLE_SET_CART',
    HANDLE_ADD_TO_CART = 'HANDLE_ADD_TO_CART',
    HANDLE_REMOVE_FROM_CART = 'HANDLE_REMOVE_FROM_CART',
    HANDLE_CHANGE_CART_QUANTITY = 'HANDLE_CHANGE_CART_QUANTITY',
    HANDLE_SUMMARY = 'HANDLE_SUMMARY',
}